### ISSUE TITLE
Test files should not be pulled into builds

### ISSUE THREAD

**Issue by mduvergey** [ashblue/fluid-behavior-tree#18] opened 2020-05-18 15:51 UTC
Hi,

Installing NSubstitute with Unity package manager is required in order for Fluid Behavior Tree to compile properly.

Installation guidelines should mention that.

Best regards

**Comment by ashblue** [comment] 2020-05-27 15:29
This should only be required if you're trying to run the test suite (at that point I highly suggest cloning down this repo instead) or you manually pulled the files into your project. How did you install the package? Hopefully you used the guide here?

https://github.com/ashblue/fluid-behavior-tree/blob/f0512f75701791015ed264800a5c05d23197181f/Assets/FluidBehaviorTree/Runtime/TaskParents/TaskParentBase.cs#L22

**Comment by mduvergey** [comment] 2020-05-27 20:15
I installed the package following guide instructions, adding scopedRegistries entry in file manifest.json then using Unity Package Manager to get the package.

**Comment by ashblue** [comment] 2020-05-28 01:12
Weird, haven't seen this before. Wondering if you somehow included the test files with your asmdef files. I'll try to reproduce on my end this weekend. What's your Unity version?

**Comment by mduvergey** [comment] 2020-05-28 08:05
It's 2018.4.22f1.

**Comment by ashblue** [comment] 2020-05-28 14:17
Uh oh, I think this package is marked as 2019 required at least. Big changes to the package manager since then. I'll update the install docs if this is the case.

**Comment by ashblue** [comment] 2020-05-29 20:51
Okay min is 2018.1, will investigate and update more here this weekend https://github.com/ashblue/fluid-behavior-tree/blob/master/Assets/FluidBehaviorTree/package.json#L6

**Comment by ashblue** [comment] 2020-05-30 23:21
A fresh install of 2019.3.15f1 with the library works fine. Proceeding to check 2018.4.22f1 to see if I can reproduce.

**Comment by ashblue** [comment] 2020-05-30 23:33
@mduvergey I tried your specific version and I can't reproduce this issue. Can you post the specific error message? I think it may be something specific to your setup. Are you using .asmdef files? If so don't include any of the test ones.

**Comment by mduvergey** [comment] 2020-05-31 08:22
Here is the error message:
Library/PackageCache/com.fluid.behavior-tree@2.2.1/Tests/Editor/BehaviorTrees/BehaviorTreeTest.cs(6,7): error CS0246: The type or namespace name 'NSubstitute' could not be found (are you missing a using directive or an assembly reference?)

I'm not using .asmdef files.

One interesting thing I just found out is that the problem occurs with version 2.2.1 of Fluid BT but not with version 2.2.0.

**Comment by ashblue** [comment] 2020-05-31 17:05
That gives me an idea, going to try fiddling with some settings.

**Comment by ashblue** [comment] 2020-05-31 17:09
Yep, able to confirm, I'll try to get this patched asap.

**Comment by ashblue** [comment] 2020-05-31 17:25
I found the issue. Looks like the editor file was mangled on Unity upgrade. https://github.com/ashblue/fluid-behavior-tree/compare/v2.2.0...v2.2.1#diff-0fe051f82fee31b8860f0c4d27fce39a

**Comment by ashblue** [comment] 2020-05-31 17:50
Heyo, I got a fix into the nightly build which seems to be working fine. If you have some time you can try it out here (no pressure though).

https://github.com/ashblue/fluid-behavior-tree#nightly-builds

This will go out in the next release. I need to fix another bug with composites. Once that's done the two should go out together in a patch.

PS Thank you super duper much for your patience with reporting this. Will add you as a contributor for the stellar bug report.

**Comment by ashblue** [comment] 2020-05-31 17:52
@all-contributors please add mduvergey for 🐛

**Comment by ashblue** [comment] 2020-05-31 17:53
@all-contributors please add mduvergey for bug

**Comment by mduvergey** [comment] 2020-05-31 18:09
Hi,
I can confirm that your fix works.
Thanks!

**Closed** 2020-06-04 01:48 UTC
Labels: bug
